server:
  port: 7807
spring:
  application:
     name: springcloud-eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com.zc.feign.UserFeignClient:DEBUG