server:
  port: 7901
user: 
  userServicePath: http://localhost:7900/simple/
spring:
  application:
     name: springcloud-eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true