spring:
  application:
    name: gateway-zuul
server:
  port: 8999
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    springcloud-eureka-provider:
      /user/**   