server:
  port: 7804
spring:
  application:
     name: springcloud-eureka-consumer-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
   enabled: false
springcloud-eureka-provider1:
  ribbon:
    listOfServers: localhost:7903